# Background opacity
#
# Window opacity as a floating point number from `0.0` to `1.0`.
# The value `0.0` is completely transparent and `1.0` is opaque.
window:
  opacity: 0.9

font:
  normal:
    family: hack
    style: Regular

  bold:
    family: hack
    style: Bold

  italic:
    family: hack
    style: Italic

  bold_italic:
    family: hack
    style: Bold Italic

  size: 11
